// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsRecordType = { id: string, record_type: string, name: string, content: string, ttl: number, proxied: boolean, };
